[execution]
user_script_path = "/tmp/user_script.sh"
status_put_url = ""
poke_url = ""
run_id = ""
node_name = ""
log_level = "info"
logs_put_url = ""
log_upload_interval_ms = 5000

[log]
level = "warn"

[workspace]
get_url = ""
dir = "/workspace"
